### ISSUE TITLE
Uglify.js error with make

### ISSUE THREAD

**Issue by kittykatattack** [kittykatattack/hexi#33]
Running `make` on in the root generates this error generated by uglify.js:
```
uglifyjs bin/hexi.js --output bin/hexi.min.js
Parse error at bin/hexi.js:37302,3
Unexpected token: operator (=)
Error
    at new JS_Parse_Error (eval at <anonymous> (/usr/local/lib/node_modules/uglify-js/tools/node.js:22:1), <anonymous>:1526:18)
    at js_error (eval at <anonymous> (/usr/local/lib/node_modules/uglify-js/tools/node.js:22:1), <anonymous>:1534:11)
    at croak (eval at <anonymous> (/usr/local/lib/node_modules/uglify-js/tools/node.js:22:1), <anonymous>:2025:9)
    at token_error (eval at <anonymous> (/usr/local/lib/node_modules/uglify-js/tools/node.js:22:1), <anonymous>:2033:9)
    at unexpected (eval at <anonymous> (/usr/local/lib/node_modules/uglify-js/tools/node.js:22:1), <anonymous>:2039:9)
    at expr_atom (eval at <anonymous> (/usr/local/lib/node_modules/uglify-js/tools/node.js:22:1), <anonymous>:2546:9)
    at maybe_unary (eval at <anonymous> (/usr/local/lib/node_modules/uglify-js/tools/node.js:22:1), <anonymous>:2708:19)
    at expr_op (eval at <anonymous> (/usr/local/lib/node_modules/uglify-js/tools/node.js:22:1), <anonymous>:2730:33)
    at expr_ops (eval at <anonymous> (/usr/local/lib/node_modules/uglify-js/tools/node.js:22:1), <anonymous>:2743:16)
    at maybe_conditional (eval at <anonymous> (/usr/local/lib/node_modules/uglify-js/tools/node.js:22:1), <anonymous>:2748:20)
    at maybe_assign (eval at <anonymous> (/usr/local/lib/node_modules/uglify-js/tools/node.js:22:1), <anonymous>:2772:20)
    at expression (eval at <anonymous> (/usr/local/lib/node_modules/uglify-js/tools/node.js:22:1), <anonymous>:2791:20)
    at simple_statement (eval at <anonymous> (/usr/local/lib/node_modules/uglify-js/tools/node.js:22:1), <anonymous>:2239:55)
make: *** [minify] Error 1
```
37302 is this bit of code in `hexi.js`:
```
 return TileUtilities;
})();
//# sourceMappingURL=tileUtilities.js.map/*
Hexi
====
```
The `/*` needs to wrap to the next line to start the comment section (for some reason it's adding it on the previous line)
Something strange with with wither babelJS, cat, or uglifyJS.

**Comment by kittykatattack** [comment]
Looks like it might be babel that's not configured properly locally... I will check.

**Comment by kittykatattack** [comment]
Yup, babel wasn't configured properly!
Solved now.
